name: Hello World!

on:
  push:
    branches:
      - main

jobs:
  hello_world_job:
    runs-on: windows-2022
    steps:
      - name: Say hello
        run: |
          echo "Hello World!"
      - name: Now it is
        run: date
      - name: Directory content
        shell: pwsh
        run: |
          Get-ChildItem | Select-Object Mode, LastWriteTime, Length, Name
